package administraScan;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Juan
 */
public class frmAdministraScan extends javax.swing.JFrame {
    
    /**
     * Creates new form frmAdministraScan
     */
    private Dimension dim;
    SubsistemaListModel dlm;
    CentroTrabajoListModel dlmct;
    EmpleadoListModel dlmemp;
    DocumentoExpedienteListModel dlmdocob;
    DocumentoExpedienteListModel dlmdocop;
    
    public frmAdministraScan() {
        initComponents();
        dlm = new SubsistemaListModel();
        dlmct = new CentroTrabajoListModel();
        dlmemp = new EmpleadoListModel();
        dlmdocob = new DocumentoExpedienteListModel();
        dlmdocop = new DocumentoExpedienteListModel();
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtExpedientesEscaneados = new javax.swing.JLabel();
        txtExpedientesCompletos = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        panelSubSistema = new javax.swing.JPanel();
        scrollSubSistema = new javax.swing.JScrollPane();
        listaSubSistema = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        panelCT = new javax.swing.JPanel();
        scrollCT = new javax.swing.JScrollPane();
        listaCT = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        panelCURP = new javax.swing.JPanel();
        scrollPlantilla = new javax.swing.JScrollPane();
        listaPlantilla = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        panelDocumentos = new javax.swing.JPanel();
        scrollDocumentos = new javax.swing.JScrollPane();
        listaDocumentos = new javax.swing.JList();
        jLabel8 = new javax.swing.JLabel();
        PanelDocumentosSecundarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDocumentosOp = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCabecera.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel1.setText("UNIDAD DE SERVICIOS EDUCATIVOS DE TLAXCALA");

        jLabel2.setText("ESCANEO DE EXPEDIENTES LABORALES");

        jLabel3.setText("Expedientes Escaneados:");

        jLabel4.setText("Expedientes Completos:");

        txtExpedientesEscaneados.setText("100000");

        txtExpedientesCompletos.setText("100000");

        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.setLabel("Organizar Directorios");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jButton1.setText("Generar reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(txtExpedientesEscaneados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExpedientesCompletos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCabeceraLayout.createSequentialGroup()
                                .addGap(344, 344, 344)
                                .addComponent(jLabel2))
                            .addGroup(panelCabeceraLayout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(jLabel1)))
                        .addGap(0, 347, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addGroup(panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtExpedientesEscaneados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtExpedientesCompletos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGap(9, 9, 9))
                    .addGroup(panelCabeceraLayout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panelSubSistema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listaSubSistema.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        listaSubSistema.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaSubSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaSubSistema.setRequestFocusEnabled(false);
        listaSubSistema.setSelectionBackground(new java.awt.Color(153, 153, 153));
        listaSubSistema.setValueIsAdjusting(true);
        listaSubSistema.setVerifyInputWhenFocusTarget(false);
        listaSubSistema.setVisibleRowCount(0);
        listaSubSistema.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                listaSubSistemaFocusLost(evt);
            }
        });
        listaSubSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaSubSistemaMouseClicked(evt);
            }
        });
        scrollSubSistema.setViewportView(listaSubSistema);

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel5.setText("Subsistema");

        javax.swing.GroupLayout panelSubSistemaLayout = new javax.swing.GroupLayout(panelSubSistema);
        panelSubSistema.setLayout(panelSubSistemaLayout);
        panelSubSistemaLayout.setHorizontalGroup(
            panelSubSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubSistemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelSubSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSubSistemaLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(scrollSubSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        panelSubSistemaLayout.setVerticalGroup(
            panelSubSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubSistemaLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelSubSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSubSistemaLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(scrollSubSistema, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelCT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listaCT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        listaCT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaCT.setFocusable(false);
        listaCT.setRequestFocusEnabled(false);
        listaCT.setSelectionBackground(new java.awt.Color(153, 153, 153));
        listaCT.setVerifyInputWhenFocusTarget(false);
        listaCT.setVisibleRowCount(0);
        listaCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCTMouseClicked(evt);
            }
        });
        scrollCT.setViewportView(listaCT);

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel6.setText("Centros de Trabajo");

        javax.swing.GroupLayout panelCTLayout = new javax.swing.GroupLayout(panelCT);
        panelCT.setLayout(panelCTLayout);
        panelCTLayout.setHorizontalGroup(
            panelCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
            .addGroup(panelCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCTLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(scrollCT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        panelCTLayout.setVerticalGroup(
            panelCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCTLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCTLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(scrollCT, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelCURP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listaPlantilla.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        listaPlantilla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaPlantilla.setFocusable(false);
        listaPlantilla.setRequestFocusEnabled(false);
        listaPlantilla.setSelectionBackground(new java.awt.Color(153, 153, 153));
        listaPlantilla.setVerifyInputWhenFocusTarget(false);
        listaPlantilla.setVisibleRowCount(0);
        listaPlantilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPlantillaMouseClicked(evt);
            }
        });
        scrollPlantilla.setViewportView(listaPlantilla);

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel7.setText("Empleados");

        javax.swing.GroupLayout panelCURPLayout = new javax.swing.GroupLayout(panelCURP);
        panelCURP.setLayout(panelCURPLayout);
        panelCURPLayout.setHorizontalGroup(
            panelCURPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCURPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
            .addGroup(panelCURPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCURPLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(scrollPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        panelCURPLayout.setVerticalGroup(
            panelCURPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCURPLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCURPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCURPLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(scrollPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelDocumentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listaDocumentos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        listaDocumentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaDocumentos.setFocusable(false);
        listaDocumentos.setRequestFocusEnabled(false);
        listaDocumentos.setSelectionBackground(new java.awt.Color(153, 153, 153));
        listaDocumentos.setVerifyInputWhenFocusTarget(false);
        listaDocumentos.setVisibleRowCount(0);
        scrollDocumentos.setViewportView(listaDocumentos);

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel8.setText("Documentos Obligatorios");

        javax.swing.GroupLayout panelDocumentosLayout = new javax.swing.GroupLayout(panelDocumentos);
        panelDocumentos.setLayout(panelDocumentosLayout);
        panelDocumentosLayout.setHorizontalGroup(
            panelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDocumentosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelDocumentosLayout.setVerticalGroup(
            panelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocumentosLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 185, Short.MAX_VALUE))
            .addGroup(panelDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDocumentosLayout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addComponent(scrollDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        PanelDocumentosSecundarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listaDocumentosOp.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(listaDocumentosOp);

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel9.setText("Documentos Secundarios");

        javax.swing.GroupLayout PanelDocumentosSecundariosLayout = new javax.swing.GroupLayout(PanelDocumentosSecundarios);
        PanelDocumentosSecundarios.setLayout(PanelDocumentosSecundariosLayout);
        PanelDocumentosSecundariosLayout.setHorizontalGroup(
            PanelDocumentosSecundariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDocumentosSecundariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDocumentosSecundariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelDocumentosSecundariosLayout.setVerticalGroup(
            PanelDocumentosSecundariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDocumentosSecundariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSubSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelCURP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelDocumentosSecundarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSubSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCURP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelDocumentosSecundarios, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        AdministraScan adm_scan = new AdministraScan();
        OrganizaDirectorios obj=new OrganizaDirectorios();
        obj.clasificar();
        this.dlm.limpiar();
        this.dlmct.limpiar();
        this.dlmemp.limpiar();
        this.dlmdocob.limpiar();
        this.dlmdocop.limpiar();
        this.listaCT.removeAll();
        this.listaPlantilla.removeAll();
        this.listaDocumentos.removeAll();
        this.listaDocumentosOp.removeAll();
        this.listaCT.repaint();
        this.listaPlantilla.repaint();
        this.listaDocumentos.repaint();
        this.listaDocumentosOp.repaint();
        this.visualizaSubSistemas(adm_scan.verificarexpedientes());
        
    }//GEN-LAST:event_button1ActionPerformed

    private void listaSubSistemaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listaSubSistemaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_listaSubSistemaFocusLost

    private void listaSubSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaSubSistemaMouseClicked
        // TODO add your handling code here:
        SubSistema sub = this.dlm.getSubsistema(this.listaSubSistema.getSelectedIndex());
        this.dlmct.limpiar();
        this.dlmemp.limpiar();
        this.dlmdocob.limpiar();
        this.dlmdocop.limpiar();
        this.listaCT.removeAll();
        this.listaPlantilla.removeAll();
        this.listaDocumentos.removeAll();
        this.listaDocumentosOp.removeAll();
        this.listaCT.repaint();
        this.listaPlantilla.repaint();
        this.listaDocumentos.repaint();
        this.listaDocumentosOp.repaint();
        this.visualizaCTSubSistema(sub.getCentrosTrabajoSubsistema());
               // this.listaSubSistema.getSelectedIndex()
        
        
    }//GEN-LAST:event_listaSubSistemaMouseClicked

    private void listaCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCTMouseClicked
        CentroTrabajo cen = this.dlmct.getCentroTrabajo(this.listaCT.getSelectedIndex());
        this.dlmemp.limpiar();
        this.dlmdocob.limpiar();
        this.dlmdocop.limpiar();
        this.listaPlantilla.removeAll();
        this.listaDocumentos.removeAll();
        this.listaDocumentosOp.removeAll();
        this.listaPlantilla.repaint();
        this.listaDocumentos.repaint();
        this.listaDocumentosOp.repaint();
        this.visualizaEmpleados(cen.getPantillaEmpleados());
    }//GEN-LAST:event_listaCTMouseClicked

    private void listaPlantillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPlantillaMouseClicked
        Empleado em = this.dlmemp.getEmpleado(this.listaPlantilla.getSelectedIndex());
        this.dlmdocob.limpiar();
        this.dlmdocop.limpiar();
        this.listaDocumentos.removeAll();
        this.listaDocumentosOp.removeAll();
        this.listaDocumentos.repaint();
        this.listaDocumentosOp.repaint();
        this.visualizaDocumentos(em.getExpediente());
    }//GEN-LAST:event_listaPlantillaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdministraScan adm_scan = new AdministraScan();
        adm_scan.verificarexpedientes();
    }//GEN-LAST:event_jButton1ActionPerformed
    //debe de pintar en el JList listaSubSistema los subsistemas
   public void visualizaSubSistemas(ArrayList<SubSistema> arreglosubs){    
       listaSubSistema.removeAll(); 
       for (SubSistema arreglosub : arreglosubs) {
            dlm.addSubsistema(arreglosub);
        }
         for (int i=0; i<dlm.getSize();i++){
            System.out.println(dlm.getElementAt(i));
         }
        System.out.println("_________________");
        System.out.println(" "+dlm.getSize());

        listaSubSistema.setModel(dlm);
}
   //pinta en el JList listaCT la clave de todos los CT del subsistemas
   public void visualizaCTSubSistema(ArrayList<CentroTrabajo> cts){
       listaCT.removeAll();
       for (CentroTrabajo ct : cts) {
            dlmct.addCentroTrabajo(ct);
        }   
    listaCT.setModel(dlmct);
       }
   
   //pinta en el Jlist listaPlantilla la clave CURP de los empleados de ese CT
   public void visualizaEmpleados(ArrayList<Empleado> emps){
       listaPlantilla.removeAll();
       for(Empleado emp: emps){
           dlmemp.addEmpleado(emp);
       }
       listaPlantilla.setModel(dlmemp);
   }
   
   public void visualizaDocumentos(ExpedienteEmpleado docs)
   {
       RenderListaDocumento rl = new RenderListaDocumento();
       listaDocumentos.removeAll();
       listaDocumentosOp.removeAll();
       for(DocumentoExpediente doc: docs.getObligatorios())
       {
           dlmdocob.addDocumentoExpediente(doc);
       }
       listaDocumentos.setModel(dlmdocob);
       listaDocumentos.setCellRenderer(rl);
       
       for(DocumentoExpediente doc: docs.getOpcionales())
       {
           dlmdocop.addDocumentoExpediente(doc);
           
       }
       listaDocumentosOp.setModel(dlmdocop);
       listaDocumentosOp.setCellRenderer(rl);
   
   }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdministraScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdministraScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdministraScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdministraScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdministraScan obj = new AdministraScan();
                frmAdministraScan adm =new frmAdministraScan();
                adm.setVisible(true);
                //adm.visualizaSubSistemas(obj.verificarexpedientes());
                adm.repaint();
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDocumentosSecundarios;
    private java.awt.Button button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaCT;
    private javax.swing.JList listaDocumentos;
    private javax.swing.JList listaDocumentosOp;
    private javax.swing.JList listaPlantilla;
    private javax.swing.JList listaSubSistema;
    private javax.swing.JPanel panelCT;
    private javax.swing.JPanel panelCURP;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelDocumentos;
    private javax.swing.JPanel panelSubSistema;
    private javax.swing.JScrollPane scrollCT;
    private javax.swing.JScrollPane scrollDocumentos;
    private javax.swing.JScrollPane scrollPlantilla;
    private javax.swing.JScrollPane scrollSubSistema;
    private javax.swing.JLabel txtExpedientesCompletos;
    private javax.swing.JLabel txtExpedientesEscaneados;
    // End of variables declaration//GEN-END:variables
}
